#!/bin/csh -f

xterm -fg white -bg '#002300' -cr white -cm +sb -fn a14 -xrm "XTerm*selectToClipboard: true" -geometry 80x60+122+0 &
xterm -fg white -bg '#002300' -cr white -cm +sb -fn a14 -xrm "XTerm*selectToClipboard: true" -geometry 80x47-42+0 &
xterm -fg white -bg '#002300' -cr white -cm +sb -fn a14 -xrm "XTerm*selectToClipboard: true" -geometry 80x8-42-10 &

xset r rate 300 25
